name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Start SUT
        run: |
          # Запускаем приложение и ждем его готовности
          java -jar ./artifacts/app-order.jar &
          APP_PID=$!
          echo "Started app with PID: $APP_PID"
          
          # Ждем пока приложение станет доступно
          timeout 30s bash -c 'until curl -f http://localhost:9999 > /dev/null 2>&1; do sleep 1; done'
          echo "Application is ready!"

      - name: Build with Gradle
        run: |
          # Запускаем тесты с headless режимом
          ./gradlew test --info -Dselenide.headless=true