name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Install diagnostic tools
        run: sudo apt-get update && sudo apt-get install -y curl net-tools

      - name: Check port 9999 before start
        run: |
          echo "Checking port 9999 before starting app..."
          netstat -tulpn | grep 9999 || echo "Port 9999 is free"

      - name: Start SUT with diagnostics
        run: |
          echo "Starting application..."
          # Запускаем приложение с выводом логов
          java -jar ./artifacts/app-order.jar > app.log 2>&1 &
          APP_PID=$!
          echo "Application PID: $APP_PID"
          echo $APP_PID > app.pid
          
          # Ждем и проверяем запуск
          echo "Waiting for app to start..."
          for i in {1..30}; do
            if curl -s -f http://localhost:9999 > /dev/null 2>&1; then
              echo "✅ Application is running on port 9999"
              curl -s http://localhost:9999 | head -20
              break
            else
              echo "⏳ Waiting for app... attempt $i/30"
              sleep 2
            fi
          done
          
          # Проверяем процесс
          if ps -p $APP_PID > /dev/null; then
            echo "✅ Application process is running"
          else
            echo "❌ Application process died"
            cat app.log || echo "No log file"
          fi

      - name: Check application status
        run: |
          echo "Final application status check:"
          curl -v http://localhost:9999 || echo "Curl failed"
          netstat -tulpn | grep 9999 || echo "Port not found"
          ps aux | grep java || echo "No Java processes"

      - name: Build with Gradle
        run: |
          # Запускаем тесты с headless режимом и дополнительными опциями
          ./gradlew test --info -Dselenide.headless=true -Dselenide.browser=chrome